// Code generated by Kitex v0.11.3. DO NOT EDIT.

package commentsrv

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "github.com/renxingdawang/easy-tok/kitex_gen/easy/tok/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentAction(ctx context.Context, request *comment.TokCommentActionRequest, callOptions ...callopt.Option) (r *comment.TokCommentActionResponse, err error)
	CommentList(ctx context.Context, request *comment.TokCommentActionRequest, callOptions ...callopt.Option) (r *comment.TokCommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentSrvClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentSrvClient struct {
	*kClient
}

func (p *kCommentSrvClient) CommentAction(ctx context.Context, request *comment.TokCommentActionRequest, callOptions ...callopt.Option) (r *comment.TokCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, request)
}

func (p *kCommentSrvClient) CommentList(ctx context.Context, request *comment.TokCommentActionRequest, callOptions ...callopt.Option) (r *comment.TokCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, request)
}
