// Code generated by Kitex v0.11.3. DO NOT EDIT.

package favoritesrv

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	favorite "github.com/renxingdawang/easy-tok/kitex_gen/easy/tok/favorite"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FavoriteAction(ctx context.Context, request *favorite.TokFavoriteActionRequest, callOptions ...callopt.Option) (r *favorite.TokFavoriteActionResponse, err error)
	FavoriteList(ctx context.Context, request *favorite.TokFavoriteListRequest, callOptions ...callopt.Option) (r *favorite.TokFavoriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFavoriteSrvClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFavoriteSrvClient struct {
	*kClient
}

func (p *kFavoriteSrvClient) FavoriteAction(ctx context.Context, request *favorite.TokFavoriteActionRequest, callOptions ...callopt.Option) (r *favorite.TokFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, request)
}

func (p *kFavoriteSrvClient) FavoriteList(ctx context.Context, request *favorite.TokFavoriteListRequest, callOptions ...callopt.Option) (r *favorite.TokFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteList(ctx, request)
}
